# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_New.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 703)
        MainWindow.setStyleSheet("/* Every widget */\n"
"QWidget {\n"
"    background-color: transparent;\n"
"    color: #e6e6e6;\n"
"    alternate-background-color: #3d3d3d;\n"
"}\n"
"\n"
"/* Mouse tooltips */\n"
"QToolTip {\n"
"    border: 0.05em solid #323232;\n"
"    background-color: #323232;\n"
"    color: #ecf0f1;\n"
"}\n"
"\n"
"/* Define background on QDialog and QMainWindow */\n"
"QDialog, QMainWindow {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"/* Top Menu Bar */\n"
"QMenuBar::item:selected {\n"
"    background: #444444;\n"
"}\n"
"QMenu {\n"
"    background-color: #323232;\n"
"}\n"
"QMenu::item {\n"
"    padding-left: 1.5em;\n"
"    padding-right: 0.75em;\n"
"    padding-top: 0.25em;\n"
"    padding-bottom: 0.25em;\n"
"}\n"
"QMenu::item:selected {\n"
"    background: #444444;\n"
"    border: 0.05em solid #bdc3c7;\n"
"}\n"
"QMenu::item:disabled {\n"
"    background-color: #444444;\n"
"    color: #828790;\n"
"}\n"
"\n"
"/* Tool Button (Toolbar) */\n"
"QToolButton::disabled {\n"
"    background-color: #444444;\n"
"    color: #828790;\n"
"}\n"
"QToolButton::hover {\n"
"    background-color: #3d3d3d;\n"
"}\n"
"\n"
"/* Dock Widget */\n"
"QDockWidget {\n"
"    color: #e6e6e6;\n"
"    font-weight: 500;\n"
"}\n"
"QDockWidget::title {\n"
"    background: #3d3d3d;\n"
"    padding-top: 0.20em;\n"
"    padding-left: 0.10em;\n"
"}\n"
"/* Dock Buttons: For visibility */\n"
"QDockWidget::close-button, QDockWidget::float-button {\n"
"    background-color: #bdc3c7;\n"
"    border: 0.05em solid #000;\n"
"    border-radius: 0.3em;\n"
"}\n"
"\n"
"/* Push Buttons */\n"
"QPushButton {\n"
"    background-color: #404040;\n"
"}\n"
"QPushButton::disabled {\n"
"    background-color: #828790;\n"
"}\n"
"\n"
"/* Table headers */\n"
"QHeaderView::section {\n"
"    background-color: #222;\n"
"    padding-left: 0.2em;\n"
"    border: 0.05em solid #323232;\n"
"}\n"
"\n"
"/* Tab Widgets: Disable ugly borders */\n"
"QTabWidget::pane {\n"
"    border: 0em;\n"
"}\n"
"\n"
"/* Text Edit: Log and Debugger borders */\n"
"QTextEdit {\n"
"    border: 0.05em solid #828790;\n"
"}\n"
"\n"
"/* QTabBar (Settings Dialog) */\n"
"QTabBar::tab {\n"
"    border: 0.05em solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #333333;\n"
"    padding-left: 1em;\n"
"    padding-right: 1em;\n"
"    padding-top: 0.25em;\n"
"    padding-bottom: 0.25em;\n"
"    margin-right: -0.2em;\n"
"}\n"
"QTabBar::tab:last {\n"
"    margin-right: 0em;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 0.15em;\n"
"    background-color: #292929;\n"
"}\n"
"QTabBar::tab:hover {\n"
"    background-color: #333333;\n"
"    color: #ecf0f1;\n"
"}\n"
"\n"
"/* Group Boxes (Settings Dialog) */\n"
"QGroupBox {\n"
"    margin-top: 1em;\n"
"    font-size: 8pt;\n"
"    border: 0.05em solid #bdc3c7;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    padding: 0.3em 0.5em 0.3em 0.5em;\n"
"    color: #fff;\n"
"}\n"
"\n"
"/* Checkboxes */\n"
"QCheckBox::indicator {\n"
"    border-radius: 0.1em;\n"
"    border: 0.05em solid #ecf0f1;\n"
"    margin-top: 0.05em;\n"
"    width: 0.8em;\n"
"    height: 0.8em;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #2ecc71; /* Green */\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: #e74c3c; /* Red */\n"
"}\n"
"QCheckBox::indicator::disabled {\n"
"    background-color: #7f8c8d; /* Gray */\n"
"}\n"
"\n"
"/* Radio Buttons */\n"
"QRadioButton::indicator {\n"
"    border-radius: 0.4em;\n"
"    border: 0.05em solid;\n"
"    border-color: white;\n"
"    width: 0.8em;\n"
"    height: 0.8em;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #2ecc71; /* Green */\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: #e74c3c; /* Red */\n"
"}\n"
"QRadioButton::indicator::disabled {\n"
"    background-color: #7f8c8d; /* Gray */\n"
"}\n"
"\n"
"/* Combo Boxes */\n"
"QComboBox {\n"
"    background-color: #404040;\n"
"    color: #fff;\n"
"    border: 0.05em solid #1e1e1e;\n"
"    border-radius: 0.15em;\n"
"    padding-bottom: 0.2em;\n"
"    padding-left: 0.4em;\n"
"}\n"
"QComboBox::disabled {\n"
"    background-color: #828790;\n"
"    color: #fff;\n"
"}\n"
"\n"
"/* Spin Boxes */\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background: transparent;\n"
"    border: 0.05em solid #4d4940;\n"
"    border-radius: 0.10em;\n"
"}\n"
"\n"
"/* List Widget */\n"
"QListWidget::item:selected {\n"
"    background-color: #3d3d3d;\n"
"    color: #ecf0f1;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: #4c4b4b;\n"
"    color: #ecf0f1;\n"
"}\n"
"\n"
"\n"
"/*** RPCS3 Specifics ***/\n"
"\n"
"/* Define background on Setting Widgets,\n"
"CG Disasm, Trophy Manager, RSX Debugger\n"
"which are neither QDialog nor QMainWindow */\n"
"QWidget#coreTab, QWidget#gpuTab, QWidget#audioTab,\n"
"QWidget#inputTab, QWidget#systemTab, QWidget#networkTab,\n"
"QWidget#emulatorTab, QWidget#debugTab,\n"
"QWidget#cg_disasm, QWidget#trophy_manager {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"/* Trophy Notification Popup */\n"
"QWidget#trophy_notification_frame {\n"
"    background-color: #323232;\n"
"    color: #e6e6e6;\n"
"}\n"
"\n"
"/* Game Grid Font */\n"
"QTableWidget#game_grid {\n"
"    font-weight: 600;\n"
"    font-size: 8pt;\n"
"    font-family: Lucida Grande;\n"
"    selection-color: #e6e6e6;\n"
"}\n"
"QTableWidget#game_grid::item:selected:active {\n"
"    selection-background-color: #4c4b4b;\n"
"}\n"
"QTableWidget#game_grid::item:selected:!active {\n"
"    selection-background-color: #3d3d3d;\n"
"}\n"
"\n"
"/* Set Toolbar Slider Size */\n"
"QSlider#sizeSlider::groove:horizontal {\n"
"    border: 0em solid transparent;\n"
"    height: .3em;\n"
"    background: #fff;\n"
"}\n"
"QSlider#sizeSlider::handle:horizontal {\n"
"    width: 1em;\n"
"    margin: -.8em 0;\n"
"}\n"
"\n"
"/* Set Theme UI colors */\n"
"QLabel#gamelist_icon_background_color {\n"
"    color: transparent;\n"
"}\n"
"\n"
"/* Set Taskbar Thumbnail colors */\n"
"QLabel#thumbnail_icon_color {\n"
"    color: #444444;\n"
"}\n"
"\n"
"/* Memory Viewer */\n"
"QLabel#memory_viewer_address_panel {\n"
"    color: #00cbff; /* Font Color: Blue */\n"
"}\n"
"QLabel#memory_viewer_hex_panel {\n"
"    color: #bdc3c7; /* Font Color: Grey */\n"
"}\n"
"QLabel#memory_viewer_ascii_panel {\n"
"    color: #bdc3c7; /* Font Color: Grey */\n"
"}\n"
"\n"
"/* Debugger colors */\n"
"QLabel#debugger_frame_breakpoint {\n"
"    color: #000000; /* Font Color: Black */\n"
"    background-color: #ffff00; /* Yellow */\n"
"}\n"
"QLabel#debugger_frame_pc {\n"
"    color: #000000; /* Font Color: Black */\n"
"    background-color: #00ff00; /* Green */\n"
"}\n"
"\n"
"/* Set Log colors */\n"
"QTextEdit#log_frame {\n"
"    background-color: #000000; /* Black */\n"
"}\n"
"QLabel#log_level_always {\n"
"    color: #00ffff; /* Cyan */\n"
"}\n"
"QLabel#log_level_fatal {\n"
"    color: #ff00ff; /* Fuchsia */\n"
"}\n"
"QLabel#log_level_error {\n"
"    color: #ff0000; /* Red */\n"
"}\n"
"QLabel#log_level_todo {\n"
"    color: #ff6000; /* Orange */\n"
"}\n"
"QLabel#log_level_success {\n"
"    color: #00ff00; /* Green */\n"
"}\n"
"QLabel#log_level_warning {\n"
"    color: #ffff00; /* Yellow */\n"
"}\n"
"QLabel#log_level_notice {\n"
"    color: #ffffff; /* White */\n"
"}\n"
"QLabel#log_level_trace {\n"
"    color: #808080; /* Gray */\n"
"}\n"
"QLabel#log_stack {\n"
"    color: #ffffff; /* White */\n"
"}\n"
"/* Set TTY colors */\n"
"QTextEdit#tty_frame {\n"
"    background-color: #000000; /* Black */\n"
"}\n"
"QLabel#tty_text {\n"
"    color: #ffffff; /* White */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(90, 30, 891, 551))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 891, 458))
        self.page.setObjectName("page")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_2.setGeometry(QtCore.QRect(180, 160, 511, 51))
        self.textBrowser_2.setStyleSheet("width: 250px;\n"
"height: 30px;\n"
"margin: 0 auto;\n"
"position: absolute;\n"
"top: 50%;\n"
"left: 50%;\n"
"transform: translate(-50%, -50%);\n"
"text-align: center;\n"
"border: 2px solid rgb(255, 255, 255);\n"
"line-height: 40px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_1.setGeometry(QtCore.QRect(360, 50, 121, 51))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_3.setGeometry(QtCore.QRect(170, 280, 541, 41))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 891, 458))
        self.page_2.setObjectName("page_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_1.setGeometry(QtCore.QRect(380, 370, 141, 51))
        self.pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1.setObjectName("pushButton_1")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(520, 83, 251, 191))
        self.label_2.setStyleSheet("background-color: white;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_1 = QtWidgets.QLabel(self.page_2)
        self.label_1.setGeometry(QtCore.QRect(120, 83, 251, 191))
        self.label_1.setStyleSheet("background-color: white;")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.page_2)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(390, 163, 31, 41))
        self.commandLinkButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_2.setStyleSheet("QCommandLinkButton {\n"
"    padding: 10px 20px;\n"
"    background-color: rgb(71, 71, 71);\n"
"    color: white;\n"
"    text-align: center;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"\n"
"QCommandLinkButton:hover {\n"
"    \n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"QCommandLinkButton:pressed {\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QCommandLinkButton:focus {\n"
"    outline: none; /* إزالة الحدود عند التركيز */\n"
"}\n"
"")
        self.commandLinkButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Pics/r.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_2.setIcon(icon)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_1 = QtWidgets.QCommandLinkButton(self.page_2)
        self.commandLinkButton_1.setGeometry(QtCore.QRect(70, 163, 31, 41))
        self.commandLinkButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_1.setStyleSheet("QCommandLinkButton {\n"
"    padding: 10px 20px;\n"
"    background-color: rgb(71, 71, 71);\n"
"    color: white;\n"
"    text-align: left;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"\n"
"QCommandLinkButton:hover {\n"
"    \n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"QCommandLinkButton:pressed {\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QCommandLinkButton:focus {\n"
"    outline: none; /* إزالة الحدود عند التركيز */\n"
"}\n"
"")
        self.commandLinkButton_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Pics/l.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_1.setIcon(icon1)
        self.commandLinkButton_1.setObjectName("commandLinkButton_1")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_5.setGeometry(QtCore.QRect(160, 290, 171, 31))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_6.setGeometry(QtCore.QRect(560, 290, 171, 31))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_4.setGeometry(QtCore.QRect(310, 20, 256, 41))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 891, 458))
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(520, 60, 251, 191))
        self.label_6.setStyleSheet("background-color: white;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(120, 60, 251, 191))
        self.label_5.setStyleSheet("background-color: white;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.page_3)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(390, 140, 31, 41))
        self.commandLinkButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_4.setStyleSheet("QCommandLinkButton {\n"
"    padding: 10px 20px;\n"
"    background-color: rgb(71, 71, 71);\n"
"    color: white;\n"
"    text-align: center;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"\n"
"QCommandLinkButton:hover {\n"
"    \n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"QCommandLinkButton:pressed {\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QCommandLinkButton:focus {\n"
"    outline: none; /* إزالة الحدود عند التركيز */\n"
"}\n"
"")
        self.commandLinkButton_4.setText("")
        self.commandLinkButton_4.setIcon(icon)
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.page_3)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(70, 140, 31, 41))
        self.commandLinkButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_3.setStyleSheet("QCommandLinkButton {\n"
"    padding: 10px 20px;\n"
"    background-color: rgb(71, 71, 71);\n"
"    color: white;\n"
"    text-align: left;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"\n"
"QCommandLinkButton:hover {\n"
"    \n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"QCommandLinkButton:pressed {\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QCommandLinkButton:focus {\n"
"    outline: none; /* إزالة الحدود عند التركيز */\n"
"}\n"
"")
        self.commandLinkButton_3.setText("")
        self.commandLinkButton_3.setIcon(icon1)
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.comboBox = QtWidgets.QComboBox(self.page_3)
        self.comboBox.setGeometry(QtCore.QRect(220, 320, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 400, 141, 51))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_10.setGeometry(QtCore.QRect(120, 320, 91, 31))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_8.setGeometry(QtCore.QRect(150, 270, 181, 31))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_9.setGeometry(QtCore.QRect(560, 270, 181, 31))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_7.setGeometry(QtCore.QRect(320, 10, 256, 31))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.toolBox.addItem(self.page_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Nitro Team</span></p></body></html>"))
        self.textBrowser_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">HI!</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">JPEG Compression &amp; Noise Reduction</span></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self.pushButton_1.setText(_translate("MainWindow", "Processing"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Original photo</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">New photo</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">JPEG Compression</span></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Median"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Gausing"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Avg"))
        self.pushButton_2.setText(_translate("MainWindow", "Processing"))
        self.textBrowser_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Select Filter</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Original photo</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">New Photo</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Noise Reduction </span></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Page"))

import pic_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())